[package]
name = "forex_notify"
version = "0.1.0"
authors = ["daviddexter"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0"
serde = { version = ">=1.0.117", features = ["derive"] }
toml = ">=0.5.7"